version: '3.9' #version del docker-compose
services: #nombres de los contenedores a utilizar 
  python_ev: 
    build: . # indicamos la ruta del archivo Dockerfile
    image: tesseract-img
    container_name: tesseract-cont
    stdin_open: true # docker run -i
    tty: true        #docker run -t
    #Add Tesseract folder to the path so it can be used anywhere
    environment:
      - TESSDATA_PREFIX=/home/tesseract_repos/tesseract/tessdata/
    ports: #para mappear puertos "puertoAfitrion:puertoContenedor "
      - "5000:5000" 
    volumes:
      - ./sharedFolder:/home/sharedFolder
      - ./fonts:/home/fonts
      - ./trainingFont:/home/trainingFont
