version: '3.9' #version del docker-compose
services: #nombres de los contenedores a utilizar 
  python_ev: 
    build: . # indicamos la ruta del archivo Dockerfile
    image: tesseract-img
    container_name: tesseract-cont
    stdin_open: true # docker run -i
    tty: true        #docker run -t
    ports: #para mappear puertos "puertoAfitrion:puertoContenedor "
      - "5000:5000" 
    volumes:
      - ./images:/tmp/images
      - ./trainingData:/tmp/trainingData